apiVersion: v1
kind: Service
metadata:
 name: wordpress           
 labels:
  app: wordpress
spec:
 ports:
 - port: 80     
 selector:
  app: wordpress
  tier: frontend
 type: LoadBalancer  

---

apiVersion: v1
kind: PersistentVolumeClaim    
metadata:
 name: wordpress-pv-claim
 labels:
  app: wordpress
spec:
 accessModes:
 - ReadWriteOnce
 resources:
  requests:
   storage: 2Gi 

---

apiVersion: apps/v1
kind: Deployment
metadata:
 name: wordpress   
 labels:
  app: wordpress
spec:
 selector:
  matchLabels:
   app: wordpress
   tier: frontend
 strategy:
  type: Recreate
 template:
  metadata:
   labels:
    app: wordpress
    tier: frontend
  spec:
   containers:
   - image: wordpress:latest    
     name: wordpress
     env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
       secretKeyRef:       
        name: database-password
        key: password
    - name: MYSQL_PASSWORD
      valueFrom:
       secretKeyRef:
        name: user-password
        key: password
    - name: MYSQL_USER
      value: parivansh
    - name: MySQL_DATABASE
      value: mydb
    ports:
    - containerPort: 80  
     name: wordpress
     volumeMounts:   
     - name: wordpress-pvc
     mountPath: /var/www/html
   volumes:   
   - name: wordpress-pvc
     persistentVolumeClaim:
      claimName: wordpress-pv-claim